version: "3"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:5432
  back:
    build: back
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: db
      PORT: ${PORT}
      DEBUG: ${DEBUG}
      HTTP_WORKERS: ${HTTP_WORKERS-4}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
    ports:
      - 8000:${PORT}
    depends_on:
      - db
